services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://backend:8081
      # コメントアウトすると標準出力にトレースを出力します
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jaeger:4318/v1/traces
    depends_on:
      - backend
      - jaeger

  backend:
    build: ./backend
    ports:
      - "8081:8081"
    environment:
      # コメントアウトすると標準出力にトレースを出力します
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jaeger:4318/v1/traces
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.76.0
    ports:
      - "16686:16686"  # Jaeger UI
      - "4318:4318"    # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
