upstream app {
  server app:8080;
  keepalive 100; # コネクションプールのサイズ
}

server {
  listen 80;

  client_max_body_size 10m;
  root /public/;

  location ~ ^/(favicon\.ico|css/|js/|img/) {
    root /public/;
    expires 1d;
  }

  location /image/ {
    root /public/;
    expires 1d;
    try_files $uri @app;
  }

  location @app {
    internal;
    proxy_set_header Host $host;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_pass http://app;
  }

  location / {
    proxy_set_header Host $host;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_pass http://app;
  }
}
